(() => {
 const $=id=>document.getElementById(id),input=$('codeInput');
 const dictionaries={
 ru:{workspace:'РАБОЧЕЕ ПРОСТРАНСТВО',analyzer:'Анализатор',guide:'Как это работает',betaTitle:'Меньше поиска. Больше разработки.',betaText:'Начни с одного скрипта — без установки и настройки.',project:'Рабочее пространство',lightOption:'☀ Светлая',darkOption:'☾ Тёмная',title:'Хороший код начинается здесь.',subtitle:'Найди ошибку, пойми причину и возвращайся к своей игре.',stripTitle:'Твой второй взгляд на код.',stripText:'Вставь скрипт или выбери пример. Проверка Luau бесплатна.',tryExample:'Попробовать пример ↗',examples:'Примеры',exTypes:'Ошибка типа',exScope:'Область видимости',exEvents:'События Roblox',open:'Открыть',save:'Скачать',source:'Исходный код',diagnostics:'Диагностика',live:'Результаты',emptyTitle:'Посмотрим, что внутри?',emptyText:'Запусти проверку — здесь появятся найденные проблемы и рекомендации.',syntax:'Синтаксис',types:'Типы',ai:'ИИ-разбор',limit:'До 50 КБ · Код не запускается',underHint:'ИИ видит только отправленный фрагмент. Проверяй изменения в Roblox Studio.',learnMore:'Что умеет анализатор ↗',back:'← К анализатору',independent:'Независимый инструмент для Roblox',or:'или по логину'},
 en:{workspace:'WORKSPACE',analyzer:'Analyzer',guide:'How it works',betaTitle:'Less searching. More building.',betaText:'Start with one script. Nothing to install or configure.',project:'Workspace',lightOption:'☀ Light',darkOption:'☾ Dark',title:'Better code starts here.',subtitle:'Find the issue. Understand the reason. Get back to your game.',stripTitle:'A second pair of eyes for your code.',stripText:'Paste a script or pick an example. Luau checks are free.',tryExample:'Try an example ↗',examples:'Examples',exTypes:'Type mismatch',exScope:'Variable scope',exEvents:'Roblox events',open:'Open',save:'Download',source:'Source code',diagnostics:'Diagnostics',live:'Results',emptyTitle:'Let’s see what’s inside.',emptyText:'Run an analysis to see issues, explanations and suggestions here.',syntax:'Syntax',types:'Types',ai:'AI review',limit:'Up to 50 KB · No code execution',underHint:'AI only sees the submitted snippet. Verify changes in Roblox Studio.',learnMore:'What we check ↗',back:'← Back to editor',independent:'An independent tool for Roblox',or:'or use your username'}
 };
 const en=()=>document.documentElement.lang==='en';
 const examples={types:'--!strict\n-- A value and its declared type should match.\n\nlocal coins: number = "100"\nlocal reward: number = 25\n\nlocal function addReward(amount: number)\n    coins = coins + amount\n    print("New balance:", coins)\nend\n\naddReward(reward)\n',scope:'--!strict\nlocal reward = 100\nlocal hasVIP = true\n\nif hasVIP then\n    local reward = reward * 2\n    print("VIP reward:", reward)\nend\n\n-- Should this print 100 or 200?\nprint("Final reward:", reward)\n',events:'--!strict\nlocal Players = game:GetService("Players")\n\nlocal function welcomePlayer(player: Player)\n    print("Welcome, " .. player.Name)\nend\n\nPlayers.PlayerAdded:Connect(welcomePlayer)\n'};
 function translate(){const dict=dictionaries[en()?'en':'ru'];document.querySelectorAll('[data-ui]').forEach(n=>{if(dict[n.dataset.ui])n.textContent=dict[n.dataset.ui];});input.placeholder=en()?'-- Paste your Luau code here\n-- or choose an example above':'-- Вставь код Luau сюда\n-- или выбери пример сверху';}
 const words=new Set('and break continue do else elseif end export false for function if in local nil not or repeat return then true type until while'.split(' '));
 function syncScroll(){$('codeHighlight').scrollTop=input.scrollTop;$('codeHighlight').scrollLeft=input.scrollLeft;$('lineNumbers').scrollTop=input.scrollTop;}
 function render(){
  const code=input.value;const pre=$('codeHighlight');
  const fragment=document.createDocumentFragment();
  if(code.length>100000)fragment.append(document.createTextNode(code));
  else {
   const rx=/--\[(=*)\[[\s\S]*?\]\1\]|--[^\n]*|\[(=*)\[[\s\S]*?\]\2\]|"(?:\\[\s\S]|[^"\\])*"|'(?:\\[\s\S]|[^'\\])*'|\b(?:0x[\da-fA-F]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)\b|\b[A-Za-z_]\w*\b/g;
   let index=0;for(const match of code.matchAll(rx)){fragment.append(document.createTextNode(code.slice(index,match.index)));const text=match[0];let kind='';if(text.startsWith('--'))kind='comment';else if(/^["'\[]/.test(text))kind='string';else if(/^\d/.test(text))kind='number';else if(words.has(text))kind='keyword';else if(/^\s*\(/.test(code.slice(match.index+text.length)))kind='function';const node=kind?document.createElement('span'):document.createTextNode(text);if(kind){node.className='token-'+kind;node.textContent=text;}fragment.append(node);index=match.index+text.length;}fragment.append(document.createTextNode(code.slice(index)));
  }
  fragment.append(document.createTextNode('\n'));pre.replaceChildren(fragment);
  $('lineNumbers').textContent=Array.from({length:code.split('\n').length},(_,i)=>i+1).join('\n')+'\n';syncScroll();cursor();
 }
 function cursor(){const before=input.value.slice(0,input.selectionStart);const lines=before.split('\n');$('cursorPosition').textContent=`Ln ${lines.length}, Col ${lines.at(-1).length+1}`;}
 input.addEventListener('input',render);input.addEventListener('scroll',syncScroll);input.addEventListener('click',cursor);input.addEventListener('keyup',cursor);document.addEventListener('doctor:editor-update',render);
 input.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();input.setRangeText('    ',input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input',{bubbles:true}));}});
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('editorView').hidden&&!document.querySelector('dialog[open]')){e.preventDefault();if(!$('analyzeButton').disabled)$('userForm').requestSubmit();}});
 function replace(code,name){if($('analyzeButton').disabled)return false;if(input.value.trim()&&!confirm(en()?'Replace the current code? Download it first if you want to keep it.':'Заменить текущий код? Сначала скачай его, если хочешь сохранить.'))return false;input.value=code;$('fileName').textContent=name;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();return true;}
 $('exampleSelect').onchange=()=>{const key=$('exampleSelect').value;if(examples[key])replace(examples[key],key+'.luau');$('exampleSelect').value='';};
 $('exampleQuick').onclick=()=>replace(examples.types,'example.luau');
 $('openFile').onclick=()=>{if(!$('analyzeButton').disabled)$('filePicker').click();};
 $('filePicker').onchange=async()=>{const file=$('filePicker').files[0];$('filePicker').value='';if(!file)return;if(file.size>50000)return alert(en()?'Maximum file size: 50 KB.':'Максимальный размер файла — 50 КБ.');try{replace(await file.text(),file.name);}catch{alert(en()?'Could not read the file.':'Не удалось прочитать файл.');}};
 $('saveFile').onclick=()=>{const url=URL.createObjectURL(new Blob([input.value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=$('fileName').textContent.replace(/[\\/]/g,'_')||'script.luau';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('learnMore').onclick=()=>$('aboutDialog').showModal();
 function route(){const pricing=location.hash==='#pricing';$('pricing').hidden=!pricing;$('editorView').hidden=pricing;$('pricingNav').classList.toggle('active',pricing);$('editorNav').classList.toggle('active',!pricing);$('pricingNav').setAttribute('aria-current',pricing?'page':'false');$('editorNav').setAttribute('aria-current',pricing?'false':'page');}
 $('editorNav').onclick=$('backToEditor').onclick=()=>{location.hash='editor';};
 window.addEventListener('hashchange',()=>{route();if(location.hash==='#codeInput')input.focus();});
 new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});translate();render();route();
})();
